default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: 5
  username: root
  password: password
  host: db
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: chat_app_development

test:
  <<: *default
  database: chat_app_test

production:
  <<: *default
  database: chat_app_production
  username: chat_app_user
  password: <%= ENV['CHAT_APP_DATABASE_PASSWORD'] %>
